log4j.rootLogger=ERROR, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%m%n

# Désactiver les logs Kafka
log4j.logger.org.apache.kafka=ERROR
log4j.logger.org.apache.kafka.clients=ERROR
log4j.logger.org.apache.kafka.streams=ERROR
log4j.logger.org.apache.kafka.common=ERROR
log4j.logger.org.apache.zookeeper=ERROR
